config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations/registrations' }
  resources :users do
    resources :articles do
      post 'like', to: 'articles#like'
      post 'dislike', to: 'articles#dislike'
      resources :comments
    end
  end
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'articles_with_comments', to: 'articles#articles_with_comments'
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :author, class_name: 'User'
    has_many :comments
    has_many :users, through: :comments
    has_many :likes
    has_many :dislikes

    validates :title, presence: true, length: {minimum:6,maximum:100}
    validates :description, presence: true, length: {minimum:10,maximum:300}

    mount_uploader :image, ImageUploader


    def liked_by_user?(user)
        likes.where(user: user).exists?
      end
    
    def disliked_by_user?(user)
        dislikes.where(user: user).exists?
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  


  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
    @user = current_user
  end

  def new
      @article = current_user.articles.build
  end
  
  def create
      @article=current_user.articles.new(article_params)
      @article.author=current_user
    if @article.save
      flash[:notice] = "Article created successfully"
      redirect_to user_article_path(current_user, @article)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article updated successfully"
      redirect_to user_article_path(current_user, @article)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.comments.destroy_all
    @article.destroy
    redirect_to user_articles_path(current_user)
  end

  def articles_with_comments
      @articles_with_comments = Article.includes(:comments).order('articles.created_at DESC')
  end

  def like
    article = Article.find(params[:article_id])

    # Check if the user has already liked the article
    if article.liked_by_user?(current_user)
      render json: { error: "Article already liked by the user" }, status: :unprocessable_entity
    else
      if article.disliked_by_user?(current_user)
        article.dislikes.find_by(user: current_user).destroy
      end
      # Proceed with the like logic
      like = article.likes.find_or_create_by(user: current_user)
      # like.update(liked: true)
      render json: { likes: article.likes.count, dislikes: article.dislikes.count }
    end
  end

  def dislike
    article = Article.find(params[:article_id])

    # Check if the user has already disliked the article
    if article.disliked_by_user?(current_user)
      render json: { error: "Article already disliked by the user" }, status: :unprocessable_entity
    else
      if article.liked_by_user?(current_user)
        article.likes.find_by(user: current_user).destroy
      end
      # Proceed with the dislike logic
      dislike = article.dislikes.find_or_create_by(user: current_user)
      # dislike.update(liked: false)
      render json: { likes: article.likes.count, dislikes: article.dislikes.count }
    end
  end
  
  

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:image, :title, :description)
  end
end

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors" %>
      <%= form_with(model: [@article.author,@article], url: user_articles_path(@article.author), class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row mt-3">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg mt-3" %>
        </div>
      <% end %>
    </div>

    <div class="mb-3 d-flex justify-content-center">
      <%= link_to '[ Cancel and return to articles listing ]', user_articles_path(@article.author), class: "text-info text-center" %>
    </div> 
  </div>
</div>

app/views/articles/articles_with_comments.html.erb
<h1 class="text-center">Articles with Last 5 Comments</h1>

<div class="container">
    <% @articles_with_comments.each do |article| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="card-header fst-italic">
                    by - <%= article.author.username %>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= link_to article.title,user_article_path(current_user,article), class: "text-success" %></h5>
                    <p class="card-text"><%= truncate(article.description, length: 100) %></p>
                    <%= link_to "View", user_article_path(current_user,article), class: "btn btn-outline-success"%>
                    <%= link_to "Edit", edit_user_article_path(current_user,article), class: "btn btn-outline-info"%>
                    <%= link_to "Delete", user_article_path(current_user,article), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
                </div>
                <div class="card-footer text-muted">
                    <small>Comments:<% article.comments.last(5).each do |comment| %>
                            <li><%= comment.author.username %> : <%= comment.body %></li>
                            <% end %>
                    </small>
                </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit Article</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors" %>
      <%= form_with(model: [@article.author,@article], url: user_article_path(current_user,@article), method: :patch, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row mt-3">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row mt-3">
            <%= f.label :image, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
                <%= f.file_field :image, class: "form-control-file" %>
            </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg mt-3" %>
        </div>
      <% end %>
    </div>

    <div class="mb-3 d-flex justify-content-center">
      <%= link_to '[ Cancel and return to articles listing ]', user_articles_path(current_user), class: "text-info text-center" %>
    </div> 
  </div>
</div>

app/views/articles/index.html.erb
<h1 class="text-center">Latest on Alpha</h1>

<%= image_tag current_user.image.url, class: "resize-image" if current_user.image.present?  %>
<%= will_paginate @articles %>
<div class="container">
    <% @articles.each do |article| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="card-header fst-italic">
                    by - <%= article.author.username %>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= link_to article.title,user_article_path(current_user,article), class: "text-success" %></h5>
                    <p class="card-text"><%= truncate(article.description, length: 100) %></p>
                    <%= link_to "View", user_article_path(current_user,article), class: "btn btn-outline-success"%>
                    <% if can? :update, article%>
                        <%= link_to "Edit", edit_user_article_path(current_user,article), class: "btn btn-outline-info"%>
                    <% end %>
                    <% if can? :destroy, article%>
                        <%= link_to "Delete", user_article_path(current_user,article), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
                    <% end %>
                </div>
                <div class="card-footer text-muted">
                    <small>Created <%= time_ago_in_words(article.created_at) %> ago,
                    edited <%= time_ago_in_words(article.updated_at) %> ago</small>
                </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create new Article</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors" %>
      <%= form_with(model: [@article.author,@article], url: user_articles_path(current_user), class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row mt-3">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row mt-3">
            <%= f.label :image, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
                <%= f.file_field :image, class: "form-control-file" %>
            </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg mt-3" %>
        </div>
      <% end %>
    </div>

    <div class="mb-3 d-flex justify-content-center">
      <%= link_to '[ Cancel and return to articles listing ]', user_articles_path(current_user), class: "text-info text-center" %>
    </div> 
  </div>
</div>

app/views/articles/show.html.erb
<h2 class="text-center"><%= @article.title %></h2>

<%= image_tag @article.image.url, class: "resize-image" if @article.image.present?  %>

<div class="container">
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="card-header fst-italic">
                    by - <%= @article.author.username %>
                </div>
                <div class="card-body">
                    <div class="card-text"><%= simple_format(@article.description) %></div>
                    <% if can? :create, @comment %>
                        <%= link_to "Comment", new_user_article_comment_path(:author_id,@article), class: "btn btn-outline-success"%>
                    <% end %>
                    <% if can? :update, @article%>
                        <%= link_to "Edit", edit_user_article_path(:author_id,@article), class: "btn btn-outline-info"%>
                    <% end %>
                    <% if can? :destroy, @article%>
                        <%= link_to "Delete", user_article_path(:author_id,@article), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
                    <% end %>
                    <%= link_to "Return", user_articles_path(:author_id), class: "btn btn-outline-secondary"%>

                    <div>
                    <button id="like-button">Like</button>
                    <button id="dislike-button">Dislike</button>
                    <span>Likes: <span id="like-count"><%= @article.likes.count %></span></span>
                    <span>Dislikes: <span id="dislike-count"><%= @article.dislikes.count %></span></span>
                    </div>


                    <script>
                    function updateLikesDislikes(response) {
                        console.log(response);
                        document.getElementById('like-count').textContent = response.likes;
                        document.getElementById('dislike-count').textContent = response.dislikes;
                    }

                    function sendLikeRequest(articleId, userId, csrfToken) {
                        console.log(articleId, userId);
                        fetch(`/users/${userId}/articles/${articleId}/like`, {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json', 'X-CSRF-Token': csrfToken },
                        credentials: 'same-origin'
                        })
                        .then(response => response.json())
                        .then(response => console.log(response));
                    }

                    function sendDislikeRequest(articleId, userId, csrfToken) {
                        fetch(`/users/${userId}/articles/${articleId}/dislike`, {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json', 'X-CSRF-Token': csrfToken },
                        credentials: 'same-origin'
                        })
                        .then(response => response.json())
                        .then(updateLikesDislikes);
                    }

                    document.addEventListener('DOMContentLoaded', function() {
                        const likeButton = document.getElementById('like-button');
                        const dislikeButton = document.getElementById('dislike-button');
                        const articleId = <%= @article.id %>;
                        const userId = <%= @user.id %>
                        const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');

                        console.log(csrfToken);

                        likeButton.addEventListener('click', function() {
                        sendLikeRequest(articleId, userId, csrfToken);
                        });

                        dislikeButton.addEventListener('click', function() {
                        sendDislikeRequest(articleId, userId, csrfToken);
                        });
                    });
                    </script>


                </div>


                <div class="card-footer text-muted">
                    <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
                    edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
                    <!--<p><%= "#{pluralize(@article.comments.count,'user')} commented on this Article." %></p>-->
                    <p><%= pluralize(@article.comments.distinct.count(:author_id), 'user') %> commented on this Article.</p>
                    <% user_comments_count = current_user.comments.where(article_id: @article.id).count %>
                    <p><%= "You have added #{user_comments_count} #{'comment'.pluralize(user_comments_count)} on this Article." %></p>
                </div>
                </div>
            </div>
        </div>
</div>
<h2>Comments</h2>
<%= render "comments/comment" %>